/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__(cmd: string, args?: Record<string, unknown>): Promise<any>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export async function greet(create: CreateProjectData): Promise<[string, undefined] | [undefined, null]> {
try {
    return [await invoke()("greet", { create }), undefined];
} catch (e: any) {
    if(e instanceof Error) throw e;
    else return [undefined, e];
}
}

export async function createProject(create: CreateProjectData): Promise<[null, undefined] | [undefined, null]> {
try {
    return [await invoke()("create_project", { create }), undefined];
} catch (e: any) {
    if(e instanceof Error) throw e;
    else return [undefined, e];
}
}

export type CreateProjectData = { name: string }
