name: App Builder
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      app_version: ${{ steps.version.outputs.app_version }}
      date_created: ${{ steps.version.outputs.date_created }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Generate app_version
      id: version
      run: |
        echo "app_version=$(date +'%y.%-m').${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
        echo "date_created=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

    - name: Print app_version and date_created
      run: |
        echo "app_version: ${{ steps.version.outputs.app_version }}"
        echo "date_created: ${{ steps.version.outputs.date_created }}"

  release:
      needs: [prepare]
      permissions:
          contents: write
      strategy:
          fail-fast: false
          matrix:
            platform: [windows-latest, macos-latest]
      runs-on: ${{ matrix.platform }}
      defaults:
        run:
          working-directory: sources/app
      steps:
          - name: Checkout repository
            uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

          - name: Rust setup
            uses: dtolnay/rust-toolchain@stable

          - name: Setup mise
            uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4.2.4
            with:
              working_directory: sources/app

          - name: Verify tool versions
            run: |
              node --version
              yarn --version
              mise --version

          - name: Node cache
            uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
            id: node_modules_cache
            with:
              path: sources/app/node_modules
              key: ${{ runner.os }}-sast-app-node_modules-${{ hashFiles('sources/app/yarn.lock') }}
              restore-keys: ${{ runner.os }}-sast-app-node_modules-

          - name: Install dependencies and lint
            run: |
              yarn install --immutable
              yarn build:nuxt
              yarn lint

          - name: Build tauri app
            uses: tauri-apps/tauri-action@84b9d35b5fc46c1e45415bdb6144030364f7ebc5 # v0.6.2
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
              TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
              SQLX_OFFLINE: true
            with:
              projectPath: sources/app
              tagName: ${{ needs.prepare.outputs.app_version }}
              args: '-c ''{"version": "${{ needs.prepare.outputs.app_version }}"}'''
              releaseName: sast ${{ needs.prepare.outputs.app_version }}
              releaseBody: See the assets to download and install this version.
